# Generated by Django 3.0.7 on 2020-08-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subsrciption_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'NewsletterSubscription',
                'verbose_name_plural': 'NewsletterSubscriptions',
            },
        ),
        migrations.CreateModel(
            name='PrayerItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'PrayerItem',
                'verbose_name_plural': 'PrayerItems',
            },
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='testimonyPics')),
                ('testimony', models.TextField()),
            ],
            options={
                'verbose_name': 'Testimony',
                'verbose_name_plural': 'Testimonies',
            },
        ),
        migrations.CreateModel(
            name='UpcomingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('description', models.TextField()),
                ('day_of_event', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('time_of_event', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'UpcomingEvent',
                'verbose_name_plural': 'UpcomingEvents',
            },
        ),
    ]
