# Generated by Django 3.0.7 on 2020-08-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_newslettersubscription_prayeritem_testimony_upcomingevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevent',
            name='theme',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upcomingevent',
            name='description',
            field=models.TextField(default='Coming soon'),
        ),
    ]
