# Generated by Django 3.0.7 on 2020-08-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20200828_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimony',
            name='position',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
