# Generated by Django 3.0.7 on 2020-08-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_testimony_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='sermons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=200)),
                ('minister', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sermons',
            },
        ),
    ]
