# Generated by Django 3.0.7 on 2020-08-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_sermons'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermons',
            name='link',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
