# Generated by Django 3.0.7 on 2020-08-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_sermons_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermons',
            name='img',
            field=models.ImageField(default=1, upload_to='sermonpics'),
            preserve_default=False,
        ),
    ]
