# Generated by Django 3.0.7 on 2020-08-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_sermons_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermons',
            name='date',
            field=models.DateField(),
        ),
    ]
